### ISSUE TITLE
시연에 사용할 웹 페이지를 찾는다

### ISSUE THREAD

**Issue by inspirit941** [AIFactory-CallPilot/Website#1]
파일 업로드하고 STT 변환결과 받는 기능.

(업로드 -> 응답 -> 요약) ... 동기로 처리 안될 거 같은데 어떻게 할지 고민중.

서비스 응답 속도에 따라 아키텍처가 바뀌므로 시연 방식도 바뀔 예정

**Comment by juntaek118** [comment]
시연용 웹페이지는 정말 데모 틀만 만들고, 파일 업로드 기능은 없어도 되지 않을까 싶음.
다산 콜센터에서 녹음된 파일을 저장하고, 입력했다는 가정하에
우리는 그걸 STT -> summary 하는 과정만 하면 안될지
